config/routes.rb
Rails.application.routes.draw do
  
  root "questions#index"

  devise_for :users
  
  concern :commentable do 
    resource :comments
  end
  
  resources :questions, concerns: :commentable do
    resources :answers 
    resources :tags, only: [:index, :create]
  end
  
  resources :answers, only: [], concerns: :commentable

  
  

  
  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  
  has_many   :attachments, as: :attachmentable, dependent: :destroy
  has_many   :comments, as: :commentable, dependent: :destroy
  
  validates :body,    presence: true
  validates :user_id, presence: true
  
  accepts_nested_attributes_for :attachments, :allow_destroy => true
  
  
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :attachmentable, polymorphic: true
  
  mount_uploader :file, FileUploader 
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body,    presence: true
  
  belongs_to :commentable, polymorphic: true
    
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  
  
  
end

app/models/question.rb
class Question < ActiveRecord::Base
  
  belongs_to :user
  has_many   :answers, dependent: :destroy
  has_many   :attachments, as: :attachmentable, dependent: :destroy
  has_many   :comments,    as: :commentable,    dependent: :destroy
  has_many   :question_tags
  has_many   :tags, through: :question_tags
  
  validates :title, :body, presence: true 
  validates :user_id,      presence: true
  
  accepts_nested_attributes_for :attachments, allow_destroy: true
  accepts_nested_attributes_for :tags, allow_destroy: true
  
  def tag_names
    tags.pluck(:name)
  end
  
  def tag_names=(names)
    self.tags = names.split(",").map { |name| Tag.where(name: name).first_or_create! }
  end
  
end

app/models/question_tag.rb
class QuestionTag < ActiveRecord::Base
  belongs_to :question
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates :name, presence: true
  
  has_many :question_tags
  has_many :questions, through: :question_tags
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :registerable,
         :recoverable, 
	 :rememberable, 
	 :trackable, 
	 :validatable
  
  has_many :questions
  has_many :answers
  has_one :profile
  
  accepts_nested_attributes_for :profile
  
  delegate :nickname, to: :profile
  
end

app/controllers/answers_controller.rb
class AnswersController < InheritedResources::Base
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy]  
  
  respond_to :js, :html
  
  belongs_to :question
  
  def create

    create!(notice: "Вы успешно создали ответ.")
    
     # if @answer.save
     #   format.html { render partial: 'questions/answers', layout: false }
     #   format.json { render json: @answer }
     # else
     #   format.html { render text: @answer.errors.full_messages.join("\n"), status: :unprocessable_entity }
     #   format.json { render json: @answer.errors.full_messages, status: :unprocessable_entity }
     # end
    
  end 
  
  def destroy
    destroy! { parent_url }
  end
  
  

  protected
  
  def create_resource(object)
    object.user = current_user
    super
  end
  
  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:id, :file, :_destroy], comments_attributes: [:id, :body, :_destroy])
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ 
      profile_attributes: [:nickname, :website, :location, :birthday, :about_me, :avatar]
      }, :email, :password, :password_confirmation) }

    devise_parameter_sanitizer.for(:account_update) { |u| u.permit({ 
      profile_attributes: [:nickname, :website, :location, :birthday, :about_me, :avatar, :id] }, :email,
      :password, :password_confirmation, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base
  before_action :authenticate_user!
  
  respond_to :html, :json
  
  actions :create
  
  belongs_to :question, :answer, polymorphic:true

  
  
  def create

    @question = parent.is_a?(Question) ? parent : parent.question
    
    create! do |success, failure|
      success.json do
	if parent.is_a?(Question)
          PrivatePub.publish_to "/questions/#{@question.id}/comments", comment: resource.to_json
	else
          PrivatePub.publish_to "/questions/#{@question.id}/answers/comments", comment: resource.to_json
	end
        render nothing: true
	
      end
      failure.json do
        format.html { render text: resource.errors.full_messages.join("\n"), status: :unprocessable_entity }
        format.json { render json: resource.errors.full_messages, status: :unprocessable_entity }
      end
    end

  end
 
  protected
  
  
  
    def comment_params
      params.require(:comment).permit(:body)
    end 
   
end

app/controllers/questions_controller.rb
class QuestionsController < InheritedResources::Base
  before_action :authenticate_user!, only: [:new, :create, :update, :delete]  
  before_action :build_comment, only: :show
  before_action :build_attachment, only: :new
  before_action :build_tag, only: :new
  
  respond_to :html
  def create
    create!(notice: "Вы успешно создали вопрос.")
  end
  
  protected
  
  def create_resource(object)
    object.user = current_user
    super
  end
  
  def build_comment
    @comment = resource.comments.build
    resource.tags.build
  end
  
  def build_attachment
    build_resource.attachments.build
  end
 
  def build_tag
    build_resource.tags.build
  end
    
  def question_params
    params.require(:question).permit(:title, :body, :user_id, :tag_names, attachments_attributes: [:id, :file, :_destroy], comments_attributes: [:id, :body, :_destroy], tags_attributes: [:name])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    
    @questions = Question.all
    
    render 'questions/index'
    
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  
  def index
    @tag = Tag.new
    @tags = Tag.all
  end
  
  def create
    @tag = Tag.new(tag_params)
    
    if @tag.save
      redirect_to tags_path
    else
      flash[:alert] = "Tag '#{@tag.name}' " + @tag.errors.messages[:name].to_s.gsub(/[^\w,\s,(!,?,.)]/, '')
    end
    
  end
  
  def tag_params
    params.require(:tag).permit(:name, :question_id)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def setup_ext_attr(user)
    user.profile ||= user.build_profile
    user
  end
end

app/views/answers/create.js.erb
<% if resource.errors.present? %>
  <% resource.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  <% publish_to "/questions/#{parent.id}/answers" do %>
     $('.answers').html('<%= j render 'questions/answers', question: parent %>');               
  <% end %>
  $('.new_answer #answer_body').val('');
  
  $('body > .container').prepend('<div class="alert alert-success alert-dismissable"><button class="close" data-dismiss="alert" name="button" type="button">×</button>Вы успешно создали ответ.</div>')
  

<% end %>

app/views/answers/edit.js.erb
$("#answer-<%=@answer.id%>").html('<%= j render 'questions/answer_form' %>');

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('.answers').html('<%= j render 'questions/answers', question: parent  %>');
                     
<% end %>

app/views/comments/_add_comment.html.slim
.comment-errors 

= form_for [parent, parent.comments.build], remote: true, data: { type: :json } do |f| 
  p  
    = f.label :body
    = f.text_area :body
  
  p
    = f.submit 'Добавить комментарий', class: "btn btn-info"

app/views/comments/_add_comment_to_answer.html.slim
.comment-errors 

= form_for [answer, answer.comments.build], remote: true, data: { type: :json } do |f| 
  p  
    = f.label :body
    = f.text_area :body
  
  p
    = f.submit 'Добавить комментарий', class: "btn btn-info"

app/views/comments/_comment_form.html.slim
 
h2 Edit a comment:
= form_for [@question, @comment], remote: true do |f| 
  p
    = f.label :body
    = f.text_area :body
  
  p
    = f.submit

app/views/comments/_edit_comment_form.html.slim
h2 Edit a comment:
= form_for [@question, @comment], remote: true do |f| 
  p
    = f.label :body
    = f.text_area :body
  
  p
    = f.submit class: "btn btn-success"

app/views/comments/_show_comments.html.slim
- parent.comments.each do |comment|
  p style="margin-top:5px"
    = comment.body

app/views/comments/_show_comments_in_answer.html.slim
- answer.comments.each do |comment|
  p style="margin-top:5px"
    = comment.body

app/views/questions/_answer_form.html.slim
pre
  = form_for [@question, @answer], remote: true do |f|  
    = f.label :body, 'Ответ'
    = f.text_area :body
    = f.submit 'Сохранить'
    button(onclick="cancelForm()") Отмена

app/views/questions/_answers.html.slim
- parent.answers.each_with_index do |answer, id|
  - if answer.persisted?
    .answer*{ :id => "answer-#{answer.id}"}
      div class="row" style="border-top:1px solid lightgray"
        div class="col-md-1" 
          img src="//static.copiny.com/images/user-small.png" alt=""
        div class="col-md-11"
          div class="bg-success" style="padding: 5px 0px 5px 15px"
            = link_to answer.user.email
            br
            = answer.created_at

      
          p style="padding: 15px 0px 0px 15px"
            = answer.body

            .answerattach
              ul
                - answer.attachments.each do |a|
                  - if a.file.identifier != nil
                    /li = a.file.file.filename
                    li = link_to a.file.identifier, a.file.url
          
            .edit-answer
             - if user_signed_in? && answer.user == current_user
                = link_to 'Редактировать', edit_question_answer_path(answer.question, answer), remote: true
                ' |
                = link_to 'Удалить', question_answer_path(@question, answer), :method => :delete, data: {:confirm => 'Вы уверены, что хотите удалить ответ?'}

      .comments_in_answer data={answer_id: "#{answer.id}"}
        = render 'comments/show_comments', parent: answer  
        
    div class="panel-group" id="accordion" style="margin-top:5px"
     div class="panel panel-info"
      div class="panel-heading" style="background-color: #fff; border-top-right-radius: 0px; border-top-left-radius: 0px;"
        h4 class="panel-title"
          a data-toggle="collapse" data-parent="#accordion" href="#{"#collapse" + id.to_s}"  
            | Комментировать ответ
          
        
        div id="#{"collapse" + id.to_s}" class="panel-collapse collapse"
          div class="panel-body"
            .add_comment_to_answer
              = render 'comments/add_comment', parent: answer   
  
          
              

app/views/questions/_form.html.slim
p style = "padding-left: 10px"
  = f.label :title
  = f.text_field :title
p style = "padding-left: 10px"
  = f.label :body, 'Text'
  = f.text_area :body
  = f.label :tag_names
  = f.text_field :tag_names, label: 'Tags', class: "select2-container-multi", value: '' 
br
| Приложения:
    
p 
  = f.fields_for :attachments do |a|
    
    ul class="list-group"
      li class="list-group-item" 
        = a.label :file
        = a.file_field :file
        = a.link_to_remove "Удалить этот файл"
       
p 
  = f.link_to_add "Add file", :attachments,  class: "btn btn-info"
  
| &nbsp

app/views/questions/_question_tags.html.slim
.question_tags
  p
   | tags:

   - @question.tag_names.each do |t| 
     = link_to t, "#" 

app/views/questions/edit.html.slim
= nested_form_for resource do |f|
  = render partial: "form", locals: { f: f }
  p 
    = f.submit 'Редактировать',  class: "btn btn-success"
  
  

app/views/questions/index.html.slim
div class="center hero-unit"
  h1 Welcome to the QNA. 
  h2 This is presentation of my RoR skills.


  = link_to 'Ask question', new_question_path, class: "btn btn-large btn-primary"

div 
  p Recent questions

  
- collection.each do |question|
  pre
    = link_to "#{question.title}", question
    
    
      
    
    
 

app/views/questions/new.html.slim
div class="panel panel-default" 
  div class="panel-heading"
    | Задайте Ваш вопрос
  div class="panel-body"
  = nested_form_for resource do |f|
    = render partial: "form", locals: { f: f }
    p 
      = f.submit 'Create',  class: "btn btn-success"
    

app/views/questions/show.html.slim
div class="row" class="bg-info" style="padding: 20px 20px 0px 20px"
  div class="col-md-1" 
    img src="//static.copiny.com/images/user-small.png" alt=""
  div class="col-md-11"
    div class="bg-success" style="padding: 5px 0px 5px 15px"
      = link_to resource.user.email
      br
      = resource.created_at




    
    
    h4 style="padding:15px"
      = resource.title
    p style="padding-left:15px"
      = resource.body
    
    p
      = render 'question_tags'
      
    div class="panel panel-default"
      div class="panel-heading"
        div class="panel-title"
         | Отмечен лучшим ответом
      div class="panel-body"
         | Morbi at augue mauris. Etiam volutpat tortor vitae malesuada pulvinar. Maecenas id neque mi. Nunc tincidunt id risus id vulputate. Pellentesque a sapien urna. Donec hendrerit ultricies lorem, vel interdum enim semper nec. Nullam sit amet tempor felis. Aliquam sagittis enim metus, vel facilisis lorem hendrerit at. Curabitur scelerisque laoreet molestie. 
    p style="padding: 15px 0px 0px 15px"

    
    
    
      
    p Attachments:
    ul
      .questionfile
        - resource.attachments.each do |a|
          - if a.file.present?
            /li = a.file.file.filename
            li = link_to a.file.identifier, a.file.url
        
    p class="pull-right"
      - if resource.user == current_user
        = link_to 'Редактировать', edit_question_path(resource), class: "btn btn-large btn-primary"
        | &nbsp
        = link_to 'Удалить', question_path, :method => :delete, data: {:confirm => 'Вы уверены, что хотите удалить вопрос?'}, class: "btn btn-large btn-danger"

.comments data={question_id: "#{resource.id}"}
  = render 'comments/show_comments', parent: resource  
        
div class="panel-group" id="accordion" style="margin-top:5px"
  div class="panel panel-info"
      div class="panel-heading" style="background-color: #fff; border-top-right-radius: 0px; border-top-left-radius: 0px;"
        h4 class="panel-title"
          a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"  
            | Комментировать вопрос
          
        
        div id="collapseOne" class="panel-collapse collapse"
          div class="panel-body"
            .add_comment
              = render 'comments/add_comment', parent: resource     



  
    
.answers style="margin-top:15px"
  = render 'answers', parent: resource


div class="panel panel-default" style="margin-top:15px"
  div class="panel-body"
    = nested_form_for [resource, resource.answers.build], remote: true do |f|    
   
      p
        = f.label :body, 'Your answer'
        .answer-errors
        = f.text_area :body
      p
        = f.fields_for :attachments do |b|
          = b.label :file
          = b.file_field :file
          = b.link_to_remove "Удалить этот файл"
          
        
      p 
        = f.link_to_add "Add file", :attachments,  class: "btn btn-info"
        | &nbsp
        = f.submit 'Create',  class: "btn btn-success"

= subscribe_to "/questions/#{resource.id}/answers"   
= subscribe_to "/questions/#{resource.id}/comments"
= subscribe_to "/questions/#{resource.id}/answers/comments"

      
= link_to 'Назад', root_path
    
  

app/views/static_pages/home.html.slim
h1 StaticPages#home
p Find me in app/views/static_pages/home.html.slim